### ISSUE TITLE
Infografía Hilos

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/infografia-de-hilos-Nancy-0714#2]
[Infografía_Hilos_Nancy.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Nancy-0714/files/15044432/Infografia_Hilos_Nancy.pdf)

Hilos-Nancy Olivera

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenas tardes compañera, bien hecho, obtuviste 20 de 20, en base a la rúbrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
